### ISSUE TITLE
lesson 3

### ISSUE THREAD

**Issue by kateryna06** [shotok/shotok.github.io#2]
1. Леночка, давай правильно делать форматирование в css. пишем селектор и на этой же строке откывающую скобку http://joxi.ru/4vAWEqeuvqpqmW
2. Вам Олег рассказывал про комменты в css. Это ооочень хорошо писать коменты. И тебе потом будет легче и человеку который откроет твоей проект. Так наглядно понятно где какой блок находится и какие стили применяются. Следовательно когда ты начнешь расставлять комменты, то все твои стили станут по порядку. Стили для header, menu, content, footer
3. лишний блок main. Можно же спокойно повесить паддинги и на wrap
4.  С wrap нужно убрать   min-height: 100%; Он тебе ничего не дает, а следовательно этот стиль лишний
5. логотипы всегда делаются ссылками. 
6. Ты же спокойно может переместить стили с header nav ul на header nav. От этого ничего не поломается, но ты лишишься лишнего селектора. А левый отступ будет лишним (дальше расскажу почему)
7. Свойство float: left; уже делает наш элемент блочным. По этому не нужно писать еще и     display: block; если ты уже задала float (Это у тебя на лишках в меню)
8. header nav ul li сильно длинный путь. Не нужно писать длинные пути к элементам. Можно спокойно написать header nav li и этого будет достаточно. Перепроверь плиз все свои пути
9. http://joxi.ru/1bmoyebHpyM0Ay это у нас показано активное состояние, а следовательно вся эта область должна быть кликабельна. У тебя кликабелен только текст. Вот тут нашей ссылке и не хватает display:block; Чтоб она заняла всю выделенную область. 
10. У тебя при ховере твои пункты меню дергаются, а такого быть не должно. Также если ты наведешь на соседний пункт меню, то он не только должен дергаться, но и не должно быть отступа, т.е. должно быть вот так http://joxi.ru/vn2YpM0hLeoxm6
11. Почему дергаются наши лишки. Изначалько у тебя на лишках нет бордеров, но на ховер ты их добавляешь, а следовательно добавляется еще по 1 пикселю с каждой стороны. Что же делать? Или мы задаем на обычное состояние прозрачный бордер или же при ховере/эктиве сокращаем боковые падинги по 1 пикселю.
12. Ширину с aside ul лучше переместить на aside. Когда мы флоатаем блок, то ему нужно задать ширину чтоб следующий блок понял на какую ширину ему растягиваться (если ширина для него не задана фиксированная) Оно кончено и так работае, но это не совсем правильно.
13. Стили которые перечекнуты - лишние http://joxi.ru/48An1YNcZyoO2O Когда мы задаем display:block то это говорит что элемент стал блочным и он занимает всю допустимую ширину. Т.к. у тебя ширина задана на меню, то когда ты задаешь block на ссылку, то она уже сама растянется на ширину твоего меню и задавать ширину ей не нужно. Высота на ссылке также не нужна, т.к. ты ей уже задала line-height на всю высоту пункта меню
14. картинку велосипеда нужно вырезать отдельно от бордера. А бордер нужно задать при помощи стилей
15. теперь разберемся с этими блоками http://joxi.ru/aD2PNkyFDJR9r3 Это не совсем правильно просто писать div и section. Вот тут было бы хорошо задать классы что это например img-holder и для текста какой-нибудь item-description. И тег section подразумевает под собой какую-то 2 секцию, а не просто обертка для текста. Т.е. у нас есть блок с товаром и его описание. Вот это и будет наш section.
16. Левый отступ с параграфа в описании нужно переместить на обертку, а на параграф задать нижний отступ, чтоб когда ты добавишь еще 1 параграф они не прилипли друг к другу.
17. в футере лишнее свойство clear:both Это свойсто нужно когда ты хочешь очистить обтекание до/после флоатнутых элементов. А контент у тебя не флоатается. Следовательно это свойство ничего не меняет если его удалить и по этому оно лишнее.
18. в футере не нужно указывать на ссылки line-height в 40 пикселей. Тут у тебя должен быть нормальный line-height (должен быть больше минимум на 2 пикселя, иначе иногда в некоторых браузерах если текст пишется в несколько строк - буквы обрезаются) 
19. опять же на лишках у тебя стоит и display:block и float:left Ты задаешь ему блочность 2 раза
20. на футер ты уже задала высоту и еще раз ее задаешь уже на ul Зачем? Не нужна там высота на ul Убираем высоту и у нас ничего не меняется. Если не уверена нужно свойство или нет, убираем его через инспект элемент и смотрим происходит ли что нибудь, если нет, то с большей вероятность оно нам не надо.
21. копирайт можно было написать и просто в див и не оборачиваеть его в параграф. Лишняя обертка получилась у нас.

Будут вопросы, пиши в скайп

**Comment by shotok** [comment]
1) за подобное форматирование спасибо http://www.lonniebest.com/formatcss/ я сама всегда пишу 
selector{
   chtoto: 1px;
}

2) скажу честно, у меня сейчас не хватает времени чтобы смотреть семинары в записи. А он-лайн они проводятся тогда, когда я их смотреть не могу. По-этому что там говорил Олег или что он показывал - не знаю. Верстаю как могу:)

3) на мой взгляд не лишний, поскольку на #wrap вешать padding - увеличивать блок в размерах.
Либо покажите как правильно прописать чтобы не увеличивался.

4) это потому что я не стала выкладывать последнюю версию CSS где для 
html, body {
    height: 100%;
}
так что да, уберу:)

5) Абсолютно согласна:) Как я могла упустить такую мелочь - посыпаю голову пеплом:)

6) про левый отступ - по шаблону вообще хрен поймешь есть ли вообще логика какая то в размерах, а она должна быть. Пришлось подгонять на глаз.

7) я не понимаю термин "лишках"

8) да можно вообще не писать ничего все классами забабахать и вообще проблем ни каких с путаницей путей:)
.
.
.
18) Если я не задам line-height в 40 пикселей для ссылок в футере, у меня текст поднимется наверх.

UPD 30/10/2015
ушла доверстывать ДЗ №4

**Comment by kateryna06** [comment]
2) в группе в фейсбуке выкладываются все видео онлайн семинаров/вебинаров. 

3) у тебя просто уменьшится ширина wrap на 47пикселей с каждой стороны. Или же можно задать  свойсто box-sizing: border-box; и от добавления паддингов или бордеров на ширину это влиять никак не будет

6) не всегда дизайнеры рисуют хорошие и правильные макеты. И если есть или были сомнения, то можно было спросить у меня как оно должно быть

7) li 

8) да можно хоть все так оставить или наделать кучу классов, айдишников и не париться по этому поводу. Но это будет не правильно.

18) у тебе в футуре не должно быть активной области на всю высоту футера. Оно то и сейчас есть, но это не совсем правильно так писать. А выворнять можно при помощи верхнего паддинга или на li или на ul

**Comment by shotok** [comment]
2) Я знаю что выкладывают. речь о другом. что у меня время остается только ночью сейчас. но ночью с мой занятостью я предпочитаю несчастные 6 часов поспать.

18) - можно пэддингом, а можно и line-height, оно не делает активным область вокруг .

Изменения внесены.

**Comment by kateryna06** [comment]
1. комментариев в css так и нет
2. с header ul нужно убрать левый маржин
3. вот так должно выглядеть меню при ховере на LI http://joxi.ru/8ZrJxRjuVl8b2j  у тебя не должен просвечиваться бекграунд на навигации
4. класс с картинки нужно убрать. Если клент решит заменить картинку, то он должен это легко и просто, без всякого добавление классов. Ты ж картинку обернула в див. Вот на него и надо повесить этот класс и добавить стили. 
5. Картинку ты вырезала больше чем она есть на самом деле. Нужно ее перерезать с ее реальными размерами и выровнять в блоке
6. не хватает нижнего отступа в футере

**Comment by shotok** [comment]
1) Полезность комментирования зависит от сложности проекта. В данном случае нет необходимости.
2)и 3) меню подгонялось в точности под макет. если нужно было по своему разумению делать - так и надо было писать в задании, типа "меню сделать разумным, не смотреть на макет"
4) клиент если захочет поменять картинку, в настройки класса не полезет. Он поменяет только путь до картинки. Да даже  cms будет переменная именно на путь до картинки, но ни как не до классов.
6) был ведь, пропал куда то. видимо когда убирала .main

Обновление залито.

**Comment by kateryna06** [comment]
1) полезность комментариев никак не зависит от размера проекта. Если сейчас их не научиться ставить и писать правильно и структурированно css, то потом, врядли это будет делаться. Нужно сразу учиться делать все правильно и потом будет легче.

2) я вроде бы уже говорила, но еще раз повторю. Не всегда бывают правильные дизайны. Бывает что есть блок у которого должны быть, по идее, одинаковые боковые отступы, но дизайнер с одной стороны сделал 20 пикселей, а с другой 17. Это не есть правильно. По этому надо понимать где накосячил дазайнер и сделать правильно. Потому что бывает что ты делаешь все с корявами отступами, а потом клиент говорит а чего там по разному если должно быть одинаково. По этому это не придирки, а дружески

**Comment by kateryna06** [comment]
1) полезность комментариев никак не зависит от размера проекта. Если сейчас их не научиться ставить и писать правильно и структурированно css, то потом, врядли это будет делаться. Нужно сразу учиться делать все правильно и потом будет легче.

2) я вроде бы уже говорила, но еще раз повторю. Не всегда бывают правильные дизайны. Бывает что есть блок у которого должны быть, по идее, одинаковые боковые отступы, но дизайнер с одной стороны сделал 20 пикселей, а с другой 17. Это не есть правильно. По этому надо понимать где накосячил дазайнер и сделать правильно. Потому что бывает что ты делаешь все с корявами отступами, а потом клиент говорит а чего там по разному если должно быть одинаково. По этому это не придирки, а дружеский совет

3) http://joxi.ru/0KAgRDJf14YN2l тут двойной бордер. Нужно это дело пофиксить. При ховере бордеры должны накладываться друг на друга. Можно разрешить отрицательным маржином ))

4) когда клиент будет загружать картинку он не будет менять путь, он будет заново загружать картинку. Это конечно зависит от cms. Но вешать классы на картинки нужно осторожно. А тут его просто можно избежать и сделать правильно. Может же загрузиться кагтинка меньшего размера, а если оставить как ты сделала до этого, то будет выглядеть некрасиво. 

5) с img_border лучше убрать высоту. У тебя же есть секция телефонов и там явно будет высота больше. На этот див нужно просто задать верхний и нижний отступ чтоб картинка не прилипала к краям. А с картинки уберется верхний отступ

6) http://joxi.ru/WKAx0DMsdMQ8A8 навожу на Ul в футере и она у нас не подсвечивается, она у тебя схлопнулась от того что у тебя внутри элементы флоатаются. Если блок сделан правильно, то он должен подсвечиваться, иначе в другом браузере может быть беда )) Если не знаешь, что нужно написать, скажи я подскажу

**Comment by shotok** [comment]
5) "с img_border лучше убрать высоту. У тебя же есть секция телефонов и там явно будет высота больше."
Что такое "секция телефонов"?
6) высота убрана по вашему комментарию от 29 октября: "на футер ты уже задала высоту и еще раз ее задаешь уже на ul Зачем? Не нужна там высота на ul Убираем высоту и у нас ничего не меняется."
Если убрать высоту, то что тогда написать? Подсказывай.

**Comment by kateryna06** [comment]
1) http://joxi.ru/gV2V0Jvsp5Gerv вот и секция телефонов будет когда перейдешь на этот пункт меню 

2) вот не понимаю почему вы не читаете что я пишу. Делаю же это не для себя. Вот говорила же, что на body прописывает нормально font с нормальны line-height чтоб потом не писать лишние стили для параграфов. http://joxi.ru/4zAN7XBUQkxOr9 

3) http://joxi.ru/K823GM8Sox4a2O потеряла - перед приставкой (если показывает восклицательный знак - значит скорее всего что-то не так написано) И padding прописан тут 2 раза

4) http://joxi.ru/lbrRqynC5l61A1 нижний отступ лучше прописать не через родителя, а просто от параграфа, чтоб когда у  тебя будут добавляться параграфы на других страницах они не слипались

5) а теперь к твоему вопросу про высоту на списка в футере. По моему у тебя кроме высоты еще были какие-то свойства что я попросила убрать высоту и меню это не схлопывалось. А может конечно что-то и путаю. Сейчас блок схлопнулся, по этому можно или добавить обратно высоту или задать overflow:hidden

**Comment by kateryna06** [comment]
6) стили должны быть названы просто style. не нужно его нумеровать. Олег рассказывал как должны называться файлы

**Comment by shotok** [comment]
6) у меня очень много открыто разных style сейчас и мне проще по вкладкам ориентироваться что дз3 у меня все имеет номер 3.

**Comment by kateryna06** [comment]
то что тебе так удобно это не есть правильно

**Comment by shotok** [comment]
а может хватит придираться?
Вы понимаете что абсолютно отбиваете желание работать с вами?

**Comment by kateryna06** [comment]
я не придираюсь. Есть стандарты по кторым нужно называть файлы. И хотелось чтоб вы придерживались данных стандартов.

**Comment by shotok** [comment]
спрашивать что либо у вас, консультироваться и т.д.
У меня только одни сожаления что я ввязалась в это. Потому что изначально понятно стало что не мой формат.
